listening-port=3478
tls-listening-port=5349

fingerprint
lt-cred-mech
realm=<your-domain>
user=webrtc:<your-strong-password>

external-ip=<your-server-public-ip>

min-port=49152
max-port=65535

cert=/etc/letsencrypt/live/<your-domain>/fullchain.pem
pkey=/etc/letsencrypt/live/<your-domain>/privkey.pem

no-multicast-peers
stale-nonce=600
no-cli

log-file=/var/log/turnserver/turn.log
simple-log
